"""empty message

Revision ID: 5ce54342eab4
Revises: 3c26a797bf70
Create Date: 2018-04-22 16:53:11.768857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce54342eab4'
down_revision = '3c26a797bf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cash_withdrawal', ['id'])
    op.create_unique_constraint(None, 'computer', ['id'])
    op.create_unique_constraint(None, 'license', ['id'])
    op.add_column('product', sa.Column('release', sa.JSON(), nullable=False))
    op.create_unique_constraint(None, 'product', ['id'])
    op.drop_column('product', 'period')
    op.create_unique_constraint(None, 'promo_code', ['id'])
    op.create_unique_constraint(None, 'purchase', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user_', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'purchase', type_='unique')
    op.drop_constraint(None, 'promo_code', type_='unique')
    op.add_column('product', sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'release')
    op.drop_constraint(None, 'license', type_='unique')
    op.drop_constraint(None, 'computer', type_='unique')
    op.drop_constraint(None, 'cash_withdrawal', type_='unique')
    # ### end Alembic commands ###
