"""empty message

Revision ID: 76599f8b7467
Revises: 15cabc9b0a4e
Create Date: 2018-04-16 23:41:08.947826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76599f8b7467'
down_revision = '15cabc9b0a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'addon', ['id'])
    op.create_unique_constraint(None, 'computer', ['id'])
    op.create_unique_constraint(None, 'license', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.add_column('user_', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user_', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_', type_='unique')
    op.drop_column('user_', 'active')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'license', type_='unique')
    op.drop_constraint(None, 'computer', type_='unique')
    op.drop_constraint(None, 'addon', type_='unique')
    # ### end Alembic commands ###
